sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-autoprefixer
  - jekyll-minifier
  - jekyll-seo-tag

title: larsknoke.com
email: info@larsknoke.com
github_username:  larzknoke
